# Generated by Django 5.2.7 on 2026-02-14 19:32

import django.db.models.deletion
import transaction.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Voucher Type',
                'verbose_name_plural': 'Voucher Types',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'unique_together': {('company', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('narration', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_ceated_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_modified_by', to=settings.AUTH_USER_MODEL)),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.vouchertype')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[transaction.models.validate_positive])),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[transaction.models.validate_positive])),
                ('narration', models.CharField(blank=True, max_length=200)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='ledger.ledger')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='transaction.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Entery',
                'verbose_name_plural': 'Transaction Enteries',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VoucherSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.financialyear')),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.vouchertype')),
            ],
            options={
                'unique_together': {('company', 'voucher_type', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='CompanyVoucherConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbering_mode', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='AutO', max_length=10)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('prefix_separator', models.CharField(blank=True, default='/', max_length=5)),
                ('suffix_separator', models.CharField(blank=True, default='/', max_length=5)),
                ('suffix_type', models.CharField(choices=[('NONE', 'No suffix'), ('FY_SHORT', 'Financial Year (YY-YY)'), ('FY_SINGLE', 'Financial Year (YY)'), ('YEAR', 'Calendar Year (YYYY)')], default='NONE', max_length=20)),
                ('padding', models.PositiveIntegerField(default=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.vouchertype')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('company', 'voucher_type')},
            },
        ),
    ]
