# Generated by Django 5.2.7 on 2025-12-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transactionentry_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='transaction.transaction'),
        ),
    ]
