# Generated by Django 5.2.7 on 2025-12-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('transaction', '0004_alter_transactionentry_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ledger',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='ledger.ledger'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_entries', to='transaction.transaction'),
        ),
    ]
