# Generated by Django 5.2.7 on 2025-12-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('transaction', '0005_transaction_ledger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ledger',
        ),
        migrations.AlterField(
            model_name='transactionentry',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.ledger'),
        ),
        migrations.AlterField(
            model_name='transactionentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='transaction.transaction'),
        ),
    ]
