# Generated by Django 5.2.7 on 2025-12-23 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('transaction', '0006_remove_transaction_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionentry',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='ledger.ledger'),
        ),
    ]
