# Generated by Django 5.2.7 on 2026-01-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_transactionentry_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='voucher_type',
            field=models.CharField(choices=[('sales', 'sales'), ('purchase', 'purchase'), ('journal', 'journal'), ('receipt', 'receipt'), ('contra', 'contra'), ('credit_note', 'credit_note'), ('debit_note', 'debit_note'), ('delivery_note', 'delivery_note'), ('payment', 'payment')], default='sales', max_length=30),
        ),
    ]
