# Generated by Django 5.2.7 on 2026-02-14 19:31

import django.db.models.deletion
import useraccount.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('is_verified', models.BooleanField(default=False, help_text='user should be email verified')),
                ('multi_user', models.BooleanField(default=False, help_text='user should be multi company opration')),
                ('is_superuser', models.BooleanField(default=False, help_text='has all permissions', verbose_name='superuser')),
                ('is_admin', models.BooleanField(default=False, help_text='has permissions for staff.', verbose_name='admin')),
                ('is_active', models.BooleanField(default=False, help_text='user should be treated as active', verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, help_text='user should be treated as deleted', verbose_name='deleted')),
                ('verification_code', models.CharField(blank=True, default=useraccount.models.generate_code, max_length=6)),
                ('comment', models.TextField(blank=True, default='')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='last login')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_modified_by', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
