# Generated by Django 5.2.7 on 2026-02-14 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_type', models.PositiveSmallIntegerField(choices=[(0, 'Primary'), (1, 'Accounting group ( Pre defined )'), (2, 'Accounting ledger ( Created by user )')])),
                ('code', models.CharField(blank=True, choices=[('assets', 'Assets'), ('income', 'Income'), ('liabilities', 'Liabilities'), ('expenses', 'Expenses'), ('capital account', 'Capital Account'), ('cash-in-hand', 'Cash-In-Hand'), ('bank accounts', 'Bank Accounts'), ('securities & deposits (asset)', 'Securities & Deposits (Asset)'), ('loans & advances (asset)', 'Loans & advances (Asset)'), ('stock-in-hand', 'Stock-In-Hand'), ('sundry debtors', 'Sundry Debtors'), ('sundry creditors', 'Sundry Creditors'), ('duties & taxes', 'Duties & Taxes'), ('provisions', 'Provisions'), ('secured loans', 'Secured Loans'), ('unsecured loans', 'Unsecured Loans'), ('purchase accounts', 'Purchase Accounts'), ('sales accounts', 'Sales Accounts'), ('expenses direct', 'Expenses Direct'), ('expenses indirect', 'Expenses Indirect'), ('income direct', 'Income Direct'), ('income indirect', 'Income Indirect'), ('bank od a/c', 'Bank Od A/C'), ('reserves & surplus', 'Reserves & Surplus'), ('misc. expenses (asset)', 'Misc. Expenses (Asset)'), ('deposits(assets)', 'Deposits(Assets)'), ('branch/divisions', 'Branch/Divisions')], max_length=50)),
                ('name', models.CharField(error_messages='Plese Enter Uniqe Name', max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('print_name', models.CharField(blank=True, max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance_type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], default='debit', max_length=10)),
                ('is_pre_defined', models.BooleanField(default=False)),
                ('affect_gross_profits', models.BooleanField(default=False)),
                ('is_sub_ledger', models.BooleanField(default=False)),
                ('nett_debit_credit_balances_reporting', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_deleted', models.BooleanField(default=False, help_text='ledger should be treated as deleted', verbose_name='ledger_deleted')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_modified_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ledger.ledger')),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledgers',
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(condition=models.Q(('alias', None), _negated=True), fields=('company', 'name', 'alias'), name='unique_alias_if_not_null'), models.UniqueConstraint(fields=('company', 'name'), name='unique_name')],
            },
        ),
    ]
