# Generated by Django 5.2.7 on 2026-01-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='under',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='code',
            field=models.CharField(choices=[('none', 'None'), ('assets', 'Assets'), ('income', 'Income'), ('liabilities', 'Liabilities'), ('expenses', 'Expenses'), ('capital account', 'Capital Account'), ('cash-in-hand', 'Cash-In-Hand'), ('bank accounts', 'Bank Accounts'), ('securities & deposits (asset)', 'Securities & Deposits (Asset)'), ('loans & advances (asset)', 'Loans & advances (Asset)'), ('stock-in-hand', 'Stock-In-Hand'), ('sundry debtors', 'Sundry Debtors'), ('sundry creditors', 'Sundry Creditors'), ('duties & taxes', 'Duties & Taxes'), ('provisions', 'Provisions'), ('secured loans', 'Secured Loans'), ('unsecured loans', 'Unsecured Loans'), ('purchase accounts', 'Purchase Accounts'), ('sales accounts', 'Sales Accounts'), ('expenses direct', 'Expenses Direct'), ('expenses indirect', 'Expenses Indirect'), ('income direct', 'Income Direct'), ('income indirect', 'Income Indirect'), ('bank od a/c', 'Bank Od A/C'), ('reserves & surplus', 'Reserves & Surplus'), ('misc. expenses (asset)', 'Misc. Expenses (Asset)'), ('deposits(assets)', 'Deposits(Assets)'), ('branch/divisions', 'Branch/Divisions')], default='none', max_length=50),
        ),
    ]
