# Generated by Django 5.2.7 on 2026-01-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_rename_under_ledger_parent_alter_ledger_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
